#Generated by Kickstart Configurator
#platform=x86

#System language
#lang fr_FR
lang en_EN 
#Language modules to install
langsupport fr_FR
langsupport en_EN
#System keyboard
keyboard fr
#System mouse
mouse
#System timezone
timezone Europe/Paris
#Root password
rootpw --iscrypted $1$.D0VsRGb$v/Atga5beQt77210Sw8Xa0
#Initial user
user bob --fullname "" --iscrypted --password $1$5wuA1cYt$pkuE8NtzK6r8J9MK7I/IT/
#Reboot after installation
reboot
#Use text mode install
text
#Install OS instead of upgrade
install
#Use Web installation
url --url http://10.0.1.248/distrib/ubuntu1004-cd
#url --url http://us.archive.ubuntu.com/ubuntu
#System bootloader configuration
bootloader --location=mbr --md5pass=$1$zvwcdlMN$gSZt6cRJpK5djtx8Fl4gj/
#Clear the Master Boot Record
zerombr yes
#Partition clearing information
clearpart --all --initlabel 
#Disk partitioning information
part /boot --fstype ext4 --size 500 --asprimary 
part / --fstype ext4 --size 5000 
part /var --fstype ext4 --size 5000 
part swap --size 1000 
#System authorization infomation
auth  --useshadow  --enablemd5 
#Network information
network --bootproto=dhcp --device=eth0
#Firewall configuration
firewall --disabled 
#Do not configure the X Window System
skipx

%packages
@ ubuntu-desktop

# Little hack to force installation of all packages
#%post
#aptitude -yr install ubuntu-desktop
